name: Build

on:
    push:
        branches:
            - main
        paths-ignore:
            - 'docs/**'
            - 'README.md'
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    build:
        name: Build and analyze
        runs-on: ubuntu-latest
        strategy:
          matrix:
            java-version: [ 17, 21 ]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK ${{ matrix.java-version }}
              uses: actions/setup-java@v4
              with:
                java-version: ${{ matrix.java-version }}
                distribution: 'temurin'

            - name: Cache Gradle dependencies
              uses: actions/cache@v4
              with:
                path: |
                    ~/.gradle/caches
                    ~/.gradle/wrapper
                key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                restore-keys: |
                    ${{ runner.os }}-gradle-

            - name: Build
              run: ./gradlew build

            - name: Run SonarQube Analysis
              run: ./gradlew sonar
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
