name: Docs

on:
    workflow_dispatch:
    push:
        branches: [main]

jobs:
    publish:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            java-version: [ 17, 21 ]

        steps:
            - uses: actions/checkout@v4
              with:
                  persist-credentials: false

            - name: Set up JDK ${{ matrix.java-version }}
              uses: actions/setup-java@v4
              with:
                  java-version: ${{ matrix.java-version }}
                  distribution: 'temurin'

            - name: Cache Gradle dependencies
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.gradle/caches
                      ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                  restore-keys: |
                      ${{ runner.os }}-gradle-

            - name: Build documentation
              run: ./gradlew dokkaGenerate

            - name: Publish documentation
              uses: JamesIves/github-pages-deploy-action@releases/v4
              with:
                  BRANCH: gh-pages
                  FOLDER: build/dokka/html
                  TOKEN: ${{ secrets.GH_ACCESS }}
