name: Docs

on:
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  persist-credentials: false

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: 21
                  distribution: 'temurin'

            - name: Build documentation
              run: ./gradlew dokkaGenerate

            - name: Publish documentation
              uses: JamesIves/github-pages-deploy-action@releases/v4
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_ACCESS }}
              with:
                  BRANCH: gh-pages
                  FOLDER: build/dokka/html
